language: java

os:
  - linux
  - osx

before_script:
  - cd $TRAVIS_BUILD_DIR
  - curl -sSL https://deno.land/x/install/install.sh | sh
  - curl -sSL https://denopkg.com/chiefbiiko/dynamodb/start_db.sh | bash
  - $HOME/.deno/bin/deno run --allow-env --allow-net ./setup_db.ts

script:
  - ACCESS_KEY_ID=fraud SECRET_ACCESS_KEY=fraud $HOME/.deno/bin/deno run --allow-env --allow-net ./test.ts