language: java

os:
  - linux
  - osx

before_script:
  - cd $TRAVIS_BUILD_DIR
  - curl -sSL https://deno.land/x/install/install.sh | sh
  - curl -sSL https://denopkg.com/chiefbiiko/dynamodb/start_db.sh | bash
  - $HOME/.deno/bin/deno run --allow-env --allow-net ./setup_db.ts
  - $HOME/.deno/bin/deno run --allow-read=$(pwd) --allow-env --allow-net ./setup_server.ts &

script:
  - $HOME/.deno/bin/deno run --allow-env --allow-net ./test.ts
